<?php

return [
    'row-1-main-banner' => [
        'title' => 'Row 1 - Main Banner',
        'frontend_title' => 'Main Hero Banner',
        'type' => 'banner',
        'placement' => 'hero_main',
        'count' => '1 banner',
    ],
    'row-2-small-banners' => [
        'title' => 'Row 2 - Small Banners',
        'frontend_title' => 'Small Promo Banners',
        'type' => 'banner',
        'placement' => 'promo_small',
        'count' => '4 banners',
    ],
    'row-3-shop-by-categories' => [
        'title' => 'Row 3 - Shop By Categories',
        'frontend_title' => 'Shop By Categories',
        'type' => 'categories',
        'section_key' => 'shop_by_categories',
        'section_type' => 'category',
    ],
    'row-4-product-section' => [
        'title' => 'Row 4 - Product Section',
        'frontend_title' => 'Fruits & Vegetables',
        'type' => 'products',
        'section_key' => 'fruits_vegetables',
        'section_type' => 'product',
    ],
    'row-5-bank-wallet-offers' => [
        'title' => 'Row 5 - Bank & Wallet Offers',
        'frontend_title' => 'Bank & Wallet Offers',
        'type' => 'offers',
        'section_key' => 'bank_wallet_offers',
        'section_type' => 'offer',
        'placement' => 'bank_offer',
    ],
    'row-6-top-selling-special' => [
        'title' => 'Row 6 - Top Selling Items + Special Offer',
        'frontend_title' => 'Top Selling Items',
        'type' => 'products',
        'section_key' => 'top_selling_items',
        'section_type' => 'product',
    ],
    'row-7-strip-banner' => [
        'title' => 'Row 7 - Small Strip Banner',
        'frontend_title' => 'Small Strip Banner',
        'type' => 'banner',
        'placement' => 'strip_banner',
        'count' => '1 banner',
    ],
    'row-8-breakfast-dairy' => [
        'title' => 'Row 8 - Product Section',
        'frontend_title' => 'Breakfast & Dairy',
        'type' => 'products',
        'section_key' => 'breakfast_dairy',
        'section_type' => 'product',
    ],
    'row-9-chemist-store' => [
        'title' => 'Row 9 - Product Section',
        'frontend_title' => 'Chemist Store',
        'type' => 'products',
        'section_key' => 'chemists_store',
        'section_type' => 'product',
    ],
    'row-10-two-banners' => [
        'title' => 'Row 10 - Two Banners',
        'frontend_title' => 'Two Promo Banners',
        'type' => 'banner',
        'placement' => 'middle_promo',
        'count' => '2 banners',
    ],
    'row-11-drinks' => [
        'title' => 'Row 11 - Product Section',
        'frontend_title' => 'Drinks',
        'type' => 'products',
        'section_key' => 'drinks',
        'section_type' => 'product',
    ],
    'row-12-grocery-staples' => [
        'title' => 'Row 12 - Product Section',
        'frontend_title' => 'Grocery & Staples',
        'type' => 'products',
        'section_key' => 'grocery_staples',
        'section_type' => 'product',
    ],
    'row-13-delivery-banner' => [
        'title' => 'Row 13 - Delivery Banner',
        'frontend_title' => 'Delivery Banner',
        'type' => 'banner',
        'placement' => 'footer_promo',
        'count' => '2 banners',
    ],
    'row-14-personal-care' => [
        'title' => 'Row 14 - Product Section',
        'frontend_title' => 'Personal Care',
        'type' => 'products',
        'section_key' => 'personal_care',
        'section_type' => 'product',
    ],
    'row-15-kitchen-dining' => [
        'title' => 'Row 15 - Product Section',
        'frontend_title' => 'Kitchen & Dining Needs',
        'type' => 'products',
        'section_key' => 'kitchen_dining',
        'section_type' => 'product',
    ],
    'row-16-blog' => [
        'title' => 'Row 16 - Blog',
        'frontend_title' => 'Blog',
        'type' => 'blog',
        'section_key' => 'row_16_blog',
        'section_type' => 'offer',
    ],
];
